### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [bearcove/tree-sitter-x86asm#7]
Hi, I'd like to use this parser but it doesn't have a open source license (MIT, GNU 3, Apache 2.0, etc). Would you please add one?

**Comment by fasterthanlime** [comment]
> Hi, I'd like to use this parser but it doesn't have a open source license (MIT, GNU 3, Apache 2.0, etc). Would you please add one?

Done! It's Apache2+MIT

**Comment by ColinKennedy** [comment]
Thank you! For replying quickly and for writing the parser. It's been so helpful
